### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by InFerNoBeasTz** [YeetmeisterII/KoreanVocabularyLearner#1]
How do I use this, really want to learn vocab.

**Comment by YeetmeisterII** [comment]
I'm assuming you know how to use Python if you have any issues just ask.

I programmed the project in 3.8 but I believe it should be 3.6+ compatible.
The only third party library used has its PyPi page here https://pypi.org/project/hangul-romanize/.
The easiest way to run it is through the console (use a virtual environment with the dependency if you want).
You can chose a unit (currently only unit one has any lessons in it), then choose a lesson from that unit.
The chance a word in the lesson is picked is weighted based on how often you spell it correctly and is saved in a database.

I added some improvements on my local version that I have not pushed yet so I shall do that tonight. Apologies for not having it in the description. I had it up for personal use.

Note: The units and lessons are based on this website - https://www.howtostudykorean.com/
